name: Python
on:
  workflow_call:
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/**"
  push:
    branches:
      - master

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install linting and formatting dependencies
        run: python -m pip install '.[dev]'
      - name: Check formatting
        run: make checkformat
      # - name: Check linting
      #   run: make lint
      - name: Tests
        run: make test
